// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzynQNFtqU_GsN8-6JUz466eIRRnSTlHE',
    appId: '1:785693967109:web:d0eb01e774befb4e2b6d6c',
    messagingSenderId: '785693967109',
    projectId: 'unipal-update-hehehaha',
    authDomain: 'unipal-update-hehehaha.firebaseapp.com',
    storageBucket: 'unipal-update-hehehaha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4WTx6r76T6Vy7V6mlvU8AIKFGGfmHeA',
    appId: '1:785693967109:android:3fb71b97e830ecdb2b6d6c',
    messagingSenderId: '785693967109',
    projectId: 'unipal-update-hehehaha',
    storageBucket: 'unipal-update-hehehaha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaghusyrQcghsbJbsKnbrifQYmb2Emqi0',
    appId: '1:785693967109:ios:94543a266d62e3ff2b6d6c',
    messagingSenderId: '785693967109',
    projectId: 'unipal-update-hehehaha',
    storageBucket: 'unipal-update-hehehaha.appspot.com',
    iosClientId: '785693967109-c08hb5gl4n2vod3415cbvqg8b53d5q2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTinderCloneApp',
  );
}
